# General Scratch Pad

In [2]:
import polars as pl

In [3]:
from trading.utils.Pairs import Asset, Pair

In [4]:
(df := pl.read_parquet('.data/binance/exchange.parquet')).head()

shape: (5, 6)
┌────────┬───────────┬────────────┬──────────────────┬─────────────────┬────────────┐
│ symbol ┆ baseAsset ┆ quoteAsset ┆ weightedAvgPrice ┆ volume          ┆ liquidity  │
│ ---    ┆ ---       ┆ ---        ┆ ---              ┆ ---             ┆ ---        │
│ str    ┆ str       ┆ str        ┆ str              ┆ str             ┆ f64        │
╞════════╪═══════════╪════════════╪══════════════════╪═════════════════╪════════════╡
│ ETHBTC ┆ ETH       ┆ BTC        ┆ 0.07361642       ┆ 138118.65220000 ┆ 10167.8007 │
├╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┤
│ LTCBTC ┆ LTC       ┆ BTC        ┆ 0.00273173       ┆ 117249.26900000 ┆ 320.293346 │
├╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┤
│ BNBBTC ┆ BNB       ┆ BTC        ┆ 0.01037012       ┆ 101659.43400000 ┆ 1054.2205  │
├╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┤
│ NEOBTC ┆ NEO       ┆ BTC        ┆ 0.00046728       ┆ 39092.22000000  ┆ 18.267013  │
├╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┤
│ GASBTC ┆ GAS       ┆ BTC        ┆ 0.00010585       ┆ 130813.90000000 ┆ 13.846651  │
└────────┴───────────┴────────────┴──────────────────┴─────────────────┴────────────┘

In [5]:
assets = {}
for asset in [*df['baseAsset'].unique()] + [*df['quoteAsset'].unique()]:
    assets[asset] = Asset(name=asset)

In [6]:
(
    df := (
        df
            .with_columns(
                [
                pl.col('baseAsset').apply(lambda x: assets[x], return_dtype=pl.Object),
                pl.col('quoteAsset').apply(lambda x: assets[x], return_dtype=pl.Object),
                ]
            )
    )
).head()

shape: (5, 6)
┌────────┬────────────┬────────────┬──────────────────┬─────────────────┬────────────┐
│ symbol ┆ baseAsset  ┆ quoteAsset ┆ weightedAvgPrice ┆ volume          ┆ liquidity  │
│ ---    ┆ ---        ┆ ---        ┆ ---              ┆ ---             ┆ ---        │
│ str    ┆ object     ┆ object     ┆ str              ┆ str             ┆ f64        │
╞════════╪════════════╪════════════╪══════════════════╪═════════════════╪════════════╡
│ ETHBTC ┆ name='ETH' ┆ name='BTC' ┆ 0.07361642       ┆ 138118.65220000 ┆ 10167.8007 │
├╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┤
│ LTCBTC ┆ name='LTC' ┆ name='BTC' ┆ 0.00273173       ┆ 117249.26900000 ┆ 320.293346 │
├╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┤
│ BNBBTC ┆ name='BNB' ┆ name='BTC' ┆ 0.01037012       ┆ 101659.43400000 ┆ 1054.2205  │
├╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┤
│ NEOBTC ┆ name='NEO' ┆ name='BTC' ┆ 0.00046728       ┆ 39092.22000000  ┆ 18.267013  │
├╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┤
│ GASBTC ┆ name='GAS' ┆ name='BTC' ┆ 0.00010585       ┆ 130813.90000000 ┆ 13.846651  │
└────────┴────────────┴────────────┴──────────────────┴─────────────────┴────────────┘

In [26]:
(
    df := (
        df.with_column(
            pl.Series(
                values=[Pair(asset=asset, base=base) for asset, base in zip(df['baseAsset'], df['quoteAsset'])],
                name='Asset'
            )
        )
    )
).head()

shape: (5, 7)
┌────────┬────────────┬────────────┬────────────┬──────────────────┬────────────┬──────────────────┐
│ symbol ┆ baseAsset  ┆ quoteAsset ┆ weightedAv ┆ volume           ┆ liquidity  ┆ Asset            │
│ ---    ┆ ---        ┆ ---        ┆ gPrice     ┆ ---              ┆ ---        ┆ ---              │
│ str    ┆ object     ┆ object     ┆ ---        ┆ str              ┆ f64        ┆ object           │
│        ┆            ┆            ┆ str        ┆                  ┆            ┆                  │
╞════════╪════════════╪════════════╪════════════╪══════════════════╪════════════╪══════════════════╡
│ ETHBTC ┆ name='ETH' ┆ name='BTC' ┆ 0.07361642 ┆ 138118.65220000  ┆ 10167.8007 ┆ asset=Asset(name │
│        ┆            ┆            ┆            ┆                  ┆            ┆ ='ETH')          │
│        ┆            ┆            ┆            ┆                  ┆            ┆ base=Ass...      │
├╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ LTCBTC ┆ name='LTC' ┆ name='BTC' ┆ 0.00273173 ┆ 117249.26900000  ┆ 320.293346 ┆ asset=Asset(name │
│        ┆            ┆            ┆            ┆                  ┆            ┆ ='LTC')          │
│        ┆            ┆            ┆            ┆                  ┆            ┆ base=Ass...      │
├╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ BNBBTC ┆ name='BNB' ┆ name='BTC' ┆ 0.01037012 ┆ 101659.43400000  ┆ 1054.2205  ┆ asset=Asset(name │
│        ┆            ┆            ┆            ┆                  ┆            ┆ ='BNB')          │
│        ┆            ┆            ┆            ┆                  ┆            ┆ base=Ass...      │
├╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ NEOBTC ┆ name='NEO' ┆ name='BTC' ┆ 0.00046728 ┆ 39092.22000000   ┆ 18.267013  ┆ asset=Asset(name │
│        ┆            ┆            ┆            ┆                  ┆            ┆ ='NEO')          │
│        ┆            ┆            ┆            ┆                  ┆            ┆ base=Ass...      │
├╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ GASBTC ┆ name='GAS' ┆ name='BTC' ┆ 0.00010585 ┆ 130813.90000000  ┆ 13.846651  ┆ asset=Asset(name │
│        ┆            ┆            ┆            ┆                  ┆            ┆ ='GAS')          │
│        ┆            ┆            ┆            ┆                  ┆            ┆ base=Ass...      │
└────────┴────────────┴────────────┴────────────┴──────────────────┴────────────┴──────────────────┘

In [27]:
from pathlib import Path

In [33]:
[*(Path('.data') / 'binance' / 'datasets').glob('*.parquet')][0].name

'AAVEUSDT_12h.parquet'

In [36]:
*map(lambda x: x.with_suffix('').name, (Path('.data') / 'binance' / 'datasets').glob('*.parquet')),

('AAVEUSDT_12h',
 'AAVEUSDT_15m',
 'AAVEUSDT_1d',
 'AAVEUSDT_1h',
 'AAVEUSDT_1m',
 'AAVEUSDT_1w',
 'AAVEUSDT_2h',
 'AAVEUSDT_30m',
 'AAVEUSDT_3d',
 'AAVEUSDT_3m',
 'AAVEUSDT_4h',
 'AAVEUSDT_5m',
 'AAVEUSDT_6h',
 'AAVEUSDT_8h',
 'ADAUSDT_12h',
 'ADAUSDT_15m',
 'ADAUSDT_1d',
 'ADAUSDT_1h',
 'ADAUSDT_1m',
 'ADAUSDT_1w',
 'ADAUSDT_2h',
 'ADAUSDT_30m',
 'ADAUSDT_3d',
 'ADAUSDT_3m',
 'ADAUSDT_4h',
 'ADAUSDT_5m',
 'ADAUSDT_6h',
 'ADAUSDT_8h',
 'ALGOUSDT_12h',
 'ALGOUSDT_15m',
 'ALGOUSDT_1d',
 'ALGOUSDT_1h',
 'ALGOUSDT_1m',
 'ALGOUSDT_1w',
 'ALGOUSDT_2h',
 'ALGOUSDT_30m',
 'ALGOUSDT_3d',
 'ALGOUSDT_3m',
 'ALGOUSDT_4h',
 'ALGOUSDT_5m',
 'ALGOUSDT_6h',
 'ALGOUSDT_8h',
 'APEUSDT_12h',
 'APEUSDT_15m',
 'APEUSDT_1d',
 'APEUSDT_1h',
 'APEUSDT_1m',
 'APEUSDT_1w',
 'APEUSDT_2h',
 'APEUSDT_30m',
 'APEUSDT_3d',
 'APEUSDT_3m',
 'APEUSDT_4h',
 'APEUSDT_5m',
 'APEUSDT_6h',
 'APEUSDT_8h',
 'ATOMUSDT_12h',
 'ATOMUSDT_15m',
 'ATOMUSDT_1d',
 'ATOMUSDT_1h',
 'ATOMUSDT_1m',
 'ATOMUSDT_1w',
 'ATOMUSDT_2h',
 'ATOMUSDT_30m',
 'ATOMUSDT_3d',
 'ATOMUSDT_3m',
 'ATOMUSDT_4h',
 'ATOMUSDT_5m',
 'ATOMUSDT_6h',
 'ATOMUSDT_8h',
 'AVAXUSDT_12h',
 'AVAXUSDT_15m',
 'AVAXUSDT_1d',
 'AVAXUSDT_1h',
 'AVAXUSDT_1m',
 'AVAXUSDT_1w',
 'AVAXUSDT_2h',
 'AVAXUSDT_30m',
 'AVAXUSDT_3d',
 'AVAXUSDT_3m',
 'AVAXUSDT_4h',
 'AVAXUSDT_5m',
 'AVAXUSDT_6h',
 'AVAXUSDT_8h',
 'AXSUSDT_12h',
 'AXSUSDT_15m',
 'AXSUSDT_1d',
 'AXSUSDT_1h',
 'AXSUSDT_1m',
 'AXSUSDT_1w',
 'AXSUSDT_2h',
 'AXSUSDT_30m',
 'AXSUSDT_3d',
 'AXSUSDT_3m',
 'AXSUSDT_4h',
 'AXSUSDT_5m',
 'AXSUSDT_6h',
 'AXSUSDT_8h',
 'BNBUSDT_12h',
 'BNBUSDT_15m',
 'BNBUSDT_1d',
 'BNBUSDT_1h',
 'BNBUSDT_1m',
 'BNBUSDT_1w',
 'BNBUSDT_2h',
 'BNBUSDT_30m',
 'BNBUSDT_3d',
 'BNBUSDT_3m',
 'BNBUSDT_4h',
 'BNBUSDT_5m',
 'BNBUSDT_6h',
 'BNBUSDT_8h',
 'BTCUSDT_12h',
 'BTCUSDT_15m',
 'BTCUSDT_1d',
 'BTCUSDT_1h',
 'BTCUSDT_1m',
 'BTCUSDT_1w',
 'BTCUSDT_2h',
 'BTCUSDT_30m',
 'BTCUSDT_3d',
 'BTCUSDT_3m',
 'BTCUSDT_4h',
 'BTCUSDT_5m',
 'BTCUSDT_6h',
 'BTCUSDT_8h',
 'BUSDUSDT_12h',
 'BUSDUSDT_15m',
 'BUSDUSDT_1d',
 'BUSDUSDT_1h',
 'BUSDUSDT_1m',
 'BUSDUSDT_1w',
 'BUSDUSDT_2h',
 'BUSDUSDT_30m',
 'BUSDUSDT_3d',
 'BUSDUSDT_3m',
 'BUSDUSDT_4h',
 'BUSDUSDT_5m',
 'BUSDUSDT_6h',
 'BUSDUSDT_8h',
 'CRVUSDT_12h',
 'CRVUSDT_15m',
 'CRVUSDT_1d',
 'CRVUSDT_1h',
 'CRVUSDT_1m',
 'CRVUSDT_1w',
 'CRVUSDT_2h',
 'CRVUSDT_30m',
 'CRVUSDT_3d',
 'CRVUSDT_3m',
 'CRVUSDT_4h',
 'CRVUSDT_5m',
 'CRVUSDT_6h',
 'CRVUSDT_8h',
 'DARUSDT_12h',
 'DARUSDT_15m',
 'DARUSDT_1d',
 'DARUSDT_1h',
 'DARUSDT_1m',
 'DARUSDT_1w',
 'DARUSDT_2h',
 'DARUSDT_30m',
 'DARUSDT_3d',
 'DARUSDT_3m',
 'DARUSDT_4h',
 'DARUSDT_5m',
 'DARUSDT_6h',
 'DARUSDT_8h',
 'DOGEUSDT_12h',
 'DOGEUSDT_15m',
 'DOGEUSDT_1d',
 'DOGEUSDT_1h',
 'DOGEUSDT_1m',
 'DOGEUSDT_1w',
 'DOGEUSDT_2h',
 'DOGEUSDT_30m',
 'DOGEUSDT_3d',
 'DOGEUSDT_3m',
 'DOGEUSDT_4h',
 'DOGEUSDT_5m',
 'DOGEUSDT_6h',
 'DOGEUSDT_8h',
 'DOTUSDT_12h',
 'DOTUSDT_15m',
 'DOTUSDT_1d',
 'DOTUSDT_1h',
 'DOTUSDT_1m',
 'DOTUSDT_1w',
 'DOTUSDT_2h',
 'DOTUSDT_30m',
 'DOTUSDT_3d',
 'DOTUSDT_3m',
 'DOTUSDT_4h',
 'DOTUSDT_5m',
 'DOTUSDT_6h',
 'DOTUSDT_8h',
 'DYDXUSDT_12h',
 'DYDXUSDT_15m',
 'DYDXUSDT_1d',
 'DYDXUSDT_1h',
 'DYDXUSDT_1m',
 'DYDXUSDT_1w',
 'DYDXUSDT_2h',
 'DYDXUSDT_30m',
 'DYDXUSDT_3d',
 'DYDXUSDT_3m',
 'DYDXUSDT_4h',
 'DYDXUSDT_5m',
 'DYDXUSDT_6h',
 'DYDXUSDT_8h',
 'EGLDUSDT_12h',
 'EGLDUSDT_15m',
 'EGLDUSDT_1d',
 'EGLDUSDT_1h',
 'EGLDUSDT_1m',
 'EGLDUSDT_1w',
 'EGLDUSDT_2h',
 'EGLDUSDT_30m',
 'EGLDUSDT_3d',
 'EGLDUSDT_3m',
 'EGLDUSDT_4h',
 'EGLDUSDT_5m',
 'EGLDUSDT_6h',
 'EGLDUSDT_8h',
 'ENSUSDT_12h',
 'ENSUSDT_15m',
 'ENSUSDT_1d',
 'ENSUSDT_1h',
 'ENSUSDT_1m',
 'ENSUSDT_1w',
 'ENSUSDT_2h',
 'ENSUSDT_30m',
 'ENSUSDT_3d',
 'ENSUSDT_3m',
 'ENSUSDT_4h',
 'ENSUSDT_5m',
 'ENSUSDT_6h',
 'ENSUSDT_8h',
 'EOSUSDT_12h',
 'EOSUSDT_15m',
 'EOSUSDT_1d',
 'EOSUSDT_1h',
 'EOSUSDT_1m',
 'EOSUSDT_1w',
 'EOSUSDT_2h',
 'EOSUSDT_30m',
 'EOSUSDT_3d',
 'EOSUSDT_3m',
 'EOSUSDT_4h',
 'EOSUSDT_5m',
 'EOSUSDT_6h',
 'EOSUSDT_8h',
 'ETCUSDT_12h',
 'ETCUSDT_15m',
 'ETCUSDT_1d',
 'ETCUSDT_1h',
 'ETCUSDT_1m',
 'ETCUSDT_1w',
 'ETCUSDT_2h',
 'ETCUSDT_30m',
 'ETCUSDT_3d',
 'ETCUSDT_3m',
 'ETCUSDT_4h',
 'ETCUSDT_5m',
 'ETCUSDT_6h',
 'ETCUSDT_8h',
 'ETHUSDT_12h',
 'ETHUSDT_15m',
 'ETHUSDT_1d',
 'ETHUSDT_1h',
 'ETHUSDT_1m',
 'ETHUSDT_1w',
 'ETHUSDT_2h',
 'ETHUSDT_30m',
 'ETHUSDT_3d',
 'ETHUSDT_3m',
 'ETHUSDT_4h',
 'ETHUSDT_5m',
 'ETHUSDT_6h',
 'ETHUSDT_8h',
 'EURUSDT_12h',
 'EURUSDT_15m',
 'EURUSDT_1d',
 'EURUSDT_1h',
 'EURUSDT_1m',
 'EURUSDT_1w',
 'EURUSDT_2h',
 'EURUSDT_30m',
 'EURUSDT_3d',
 'EURUSDT_3m',
 'EURUSDT_4h',
 'EURUSDT_5m',
 'EURUSDT_6h',
 'EURUSDT_8h',
 'FILUSDT_12h',
 'FILUSDT_15m',
 'FILUSDT_1d',
 'FILUSDT_1h',
 'FILUSDT_1m',
 'FILUSDT_1w',
 'FILUSDT_2h',
 'FILUSDT_30m',
 'FILUSDT_3d',
 'FILUSDT_3m',
 'FILUSDT_4h',
 'FILUSDT_5m',
 'FILUSDT_6h',
 'FILUSDT_8h',
 'FTMUSDT_12h',
 'FTMUSDT_15m',
 'FTMUSDT_1d',
 'FTMUSDT_1h',
 'FTMUSDT_1m',
 'FTMUSDT_1w',
 'FTMUSDT_2h',
 'FTMUSDT_30m',
 'FTMUSDT_3d',
 'FTMUSDT_3m',
 'FTMUSDT_4h',
 'FTMUSDT_5m',
 'FTMUSDT_6h',
 'FTMUSDT_8h',
 'GALAUSDT_12h',
 'GALAUSDT_15m',
 'GALAUSDT_1d',
 'GALAUSDT_1h',
 'GALAUSDT_1m',
 'GALAUSDT_1w',
 'GALAUSDT_2h',
 'GALAUSDT_30m',
 'GALAUSDT_3d',
 'GALAUSDT_3m',
 'GALAUSDT_4h',
 'GALAUSDT_5m',
 'GALAUSDT_6h',
 'GALAUSDT_8h',
 'GALUSDT_12h',
 'GALUSDT_15m',
 'GALUSDT_1d',
 'GALUSDT_1h',
 'GALUSDT_1m',
 'GALUSDT_1w',
 'GALUSDT_2h',
 'GALUSDT_30m',
 'GALUSDT_3d',
 'GALUSDT_3m',
 'GALUSDT_4h',
 'GALUSDT_5m',
 'GALUSDT_6h',
 'GALUSDT_8h',
 'GMTUSDT_12h',
 'GMTUSDT_15m',
 'GMTUSDT_1d',
 'GMTUSDT_1h',
 'GMTUSDT_1m',
 'GMTUSDT_1w',
 'GMTUSDT_2h',
 'GMTUSDT_30m',
 'GMTUSDT_3d',
 'GMTUSDT_3m',
 'GMTUSDT_4h',
 'GMTUSDT_5m',
 'GMTUSDT_6h',
 'GMTUSDT_8h',
 'GRTUSDT_12h',
 'GRTUSDT_15m',
 'GRTUSDT_1d',
 'GRTUSDT_1h',
 'GRTUSDT_1m',
 'GRTUSDT_1w',
 'GRTUSDT_2h',
 'GRTUSDT_30m',
 'GRTUSDT_3d',
 'GRTUSDT_3m',
 'GRTUSDT_4h',
 'GRTUSDT_5m',
 'GRTUSDT_6h',
 'GRTUSDT_8h',
 'ICPUSDT_12h',
 'ICPUSDT_15m',
 'ICPUSDT_1d',
 'ICPUSDT_1h',
 'ICPUSDT_1m',
 'ICPUSDT_1w',
 'ICPUSDT_2h',
 'ICPUSDT_30m',
 'ICPUSDT_3d',
 'ICPUSDT_3m',
 'ICPUSDT_4h',
 'ICPUSDT_5m',
 'ICPUSDT_6h',
 'ICPUSDT_8h',
 'JASMYUSDT_12h',
 'JASMYUSDT_15m',
 'JASMYUSDT_1d',
 'JASMYUSDT_1h',
 'JASMYUSDT_1m',
 'JASMYUSDT_1w',
 'JASMYUSDT_2h',
 'JASMYUSDT_30m',
 'JASMYUSDT_3d',
 'JASMYUSDT_3m',
 'JASMYUSDT_4h',
 'JASMYUSDT_5m',
 'JASMYUSDT_6h',
 'JASMYUSDT_8h',
 'KNCUSDT_12h',
 'KNCUSDT_15m',
 'KNCUSDT_1d',
 'KNCUSDT_1h',
 'KNCUSDT_1m',
 'KNCUSDT_1w',
 'KNCUSDT_2h',
 'KNCUSDT_30m',
 'KNCUSDT_3d',
 'KNCUSDT_3m',
 'KNCUSDT_4h',
 'KNCUSDT_5m',
 'KNCUSDT_6h',
 'KNCUSDT_8h',
 'LINKUSDT_12h',
 'LINKUSDT_15m',
 'LINKUSDT_1d',
 'LINKUSDT_1h',
 'LINKUSDT_1m',
 'LINKUSDT_1w',
 'LINKUSDT_2h',
 'LINKUSDT_30m',
 'LINKUSDT_3d',
 'LINKUSDT_3m',
 'LINKUSDT_4h',
 'LINKUSDT_5m',
 'LINKUSDT_6h',
 'LINKUSDT_8h',
 'LTCUSDT_12h',
 'LTCUSDT_15m',
 'LTCUSDT_1d',
 'LTCUSDT_1h',
 'LTCUSDT_1m',
 'LTCUSDT_1w',
 'LTCUSDT_2h',
 'LTCUSDT_30m',
 'LTCUSDT_3d',
 'LTCUSDT_3m',
 'LTCUSDT_4h',
 'LTCUSDT_5m',
 'LTCUSDT_6h',
 'LTCUSDT_8h',
 'LUNAUSDT_12h',
 'LUNAUSDT_15m',
 'LUNAUSDT_1d',
 'LUNAUSDT_1h',
 'LUNAUSDT_1m',
 'LUNAUSDT_1w',
 'LUNAUSDT_2h',
 'LUNAUSDT_30m',
 'LUNAUSDT_3d',
 'LUNAUSDT_3m',
 'LUNAUSDT_4h',
 'LUNAUSDT_5m',
 'LUNAUSDT_6h',
 'LUNAUSDT_8h',
 'MANAUSDT_12h',
 'MANAUSDT_15m',
 'MANAUSDT_1d',
 'MANAUSDT_1h',
 'MANAUSDT_1m',
 'MANAUSDT_1w',
 'MANAUSDT_2h',
 'MANAUSDT_30m',
 'MANAUSDT_3d',
 'MANAUSDT_3m',
 'MANAUSDT_4h',
 'MANAUSDT_5m',
 'MANAUSDT_6h',
 'MANAUSDT_8h',
 'MATICUSDT_12h',
 'MATICUSDT_15m',
 'MATICUSDT_1d',
 'MATICUSDT_1h',
 'MATICUSDT_1m',
 'MATICUSDT_1w',
 'MATICUSDT_2h',
 'MATICUSDT_30m',
 'MATICUSDT_3d',
 'MATICUSDT_3m',
 'MATICUSDT_4h',
 'MATICUSDT_5m',
 'MATICUSDT_6h',
 'MATICUSDT_8h',
 'MDTUSDT_12h',
 'MDTUSDT_15m',
 'MDTUSDT_1d',
 'MDTUSDT_1h',
 'MDTUSDT_1m',
 'MDTUSDT_1w',
 'MDTUSDT_2h',
 'MDTUSDT_30m',
 'MDTUSDT_3d',
 'MDTUSDT_3m',
 'MDTUSDT_4h',
 'MDTUSDT_5m',
 'MDTUSDT_6h',
 'MDTUSDT_8h',
 'NEARUSDT_12h',
 'NEARUSDT_15m',
 'NEARUSDT_1d',
 'NEARUSDT_1h',
 'NEARUSDT_1m',
 'NEARUSDT_1w',
 'NEARUSDT_2h',
 'NEARUSDT_30m',
 'NEARUSDT_3d',
 'NEARUSDT_3m',
 'NEARUSDT_4h',
 'NEARUSDT_5m',
 'NEARUSDT_6h',
 'NEARUSDT_8h',
 'ROSEUSDT_12h',
 'ROSEUSDT_15m',
 'ROSEUSDT_1d',
 'ROSEUSDT_1h',
 'ROSEUSDT_1m',
 'ROSEUSDT_1w',
 'ROSEUSDT_2h',
 'ROSEUSDT_30m',
 'ROSEUSDT_3d',
 'ROSEUSDT_3m',
 'ROSEUSDT_4h',
 'ROSEUSDT_5m',
 'ROSEUSDT_6h',
 'ROSEUSDT_8h',
 'RUNEUSDT_12h',
 'RUNEUSDT_15m',
 'RUNEUSDT_1d',
 'RUNEUSDT_1h',
 'RUNEUSDT_1m',
 'RUNEUSDT_1w',
 'RUNEUSDT_2h',
 'RUNEUSDT_30m',
 'RUNEUSDT_3d',
 'RUNEUSDT_3m',
 'RUNEUSDT_4h',
 'RUNEUSDT_5m',
 'RUNEUSDT_6h',
 'RUNEUSDT_8h',
 'SANDUSDT_12h',
 'SANDUSDT_15m',
 'SANDUSDT_1d',
 'SANDUSDT_1h',
 'SANDUSDT_1m',
 'SANDUSDT_1w',
 'SANDUSDT_2h',
 'SANDUSDT_30m',
 'SANDUSDT_3d',
 'SANDUSDT_3m',
 'SANDUSDT_4h',
 'SANDUSDT_5m',
 'SANDUSDT_6h',
 'SANDUSDT_8h',
 'SHIBUSDT_12h',
 'SHIBUSDT_15m',
 'SHIBUSDT_1d',
 'SHIBUSDT_1h',
 'SHIBUSDT_1m',
 'SHIBUSDT_1w',
 'SHIBUSDT_2h',
 'SHIBUSDT_30m',
 'SHIBUSDT_3d',
 'SHIBUSDT_3m',
 'SHIBUSDT_4h',
 'SHIBUSDT_5m',
 'SHIBUSDT_6h',
 'SHIBUSDT_8h',
 'SLPUSDT_12h',
 'SLPUSDT_15m',
 'SLPUSDT_1d',
 'SLPUSDT_1h',
 'SLPUSDT_1m',
 'SLPUSDT_1w',
 'SLPUSDT_2h',
 'SLPUSDT_30m',
 'SLPUSDT_3d',
 'SLPUSDT_3m',
 'SLPUSDT_4h',
 'SLPUSDT_5m',
 'SLPUSDT_6h',
 'SLPUSDT_8h',
 'SOLUSDT_12h',
 'SOLUSDT_15m',
 'SOLUSDT_1d',
 'SOLUSDT_1h',
 'SOLUSDT_1m',
 'SOLUSDT_1w',
 'SOLUSDT_2h',
 'SOLUSDT_30m',
 'SOLUSDT_3d',
 'SOLUSDT_3m',
 'SOLUSDT_4h',
 'SOLUSDT_5m',
 'SOLUSDT_6h',
 'SOLUSDT_8h',
 'THETAUSDT_12h',
 'THETAUSDT_15m',
 'THETAUSDT_1d',
 'THETAUSDT_1h',
 'THETAUSDT_1m',
 'THETAUSDT_1w',
 'THETAUSDT_2h',
 'THETAUSDT_30m',
 'THETAUSDT_3d',
 'THETAUSDT_3m',
 'THETAUSDT_4h',
 'THETAUSDT_5m',
 'THETAUSDT_6h',
 'THETAUSDT_8h',
 'TRXUSDT_12h',
 'TRXUSDT_15m',
 'TRXUSDT_1d',
 'TRXUSDT_1h',
 'TRXUSDT_1m',
 'TRXUSDT_1w',
 'TRXUSDT_2h',
 'TRXUSDT_30m',
 'TRXUSDT_3d',
 'TRXUSDT_3m',
 'TRXUSDT_4h',
 'TRXUSDT_5m',
 'TRXUSDT_6h',
 'TRXUSDT_8h',
 'TUSDUSDT_12h',
 'TUSDUSDT_15m',
 'TUSDUSDT_1d',
 'TUSDUSDT_1h',
 'TUSDUSDT_1m',
 'TUSDUSDT_1w',
 'TUSDUSDT_2h',
 'TUSDUSDT_30m',
 'TUSDUSDT_3d',
 'TUSDUSDT_3m',
 'TUSDUSDT_4h',
 'TUSDUSDT_5m',
 'TUSDUSDT_6h',
 'TUSDUSDT_8h',
 'USDCUSDT_12h',
 'USDCUSDT_15m',
 'USDCUSDT_1d',
 'USDCUSDT_1h',
 'USDCUSDT_1m',
 'USDCUSDT_1w',
 'USDCUSDT_2h',
 'USDCUSDT_30m',
 'USDCUSDT_3d',
 'USDCUSDT_3m',
 'USDCUSDT_4h',
 'USDCUSDT_5m',
 'USDCUSDT_6h',
 'USDCUSDT_8h',
 'USTUSDT_12h',
 'USTUSDT_15m',
 'USTUSDT_1d',
 'USTUSDT_1h',
 'USTUSDT_1m',
 'USTUSDT_1w',
 'USTUSDT_2h',
 'USTUSDT_30m',
 'USTUSDT_3d',
 'USTUSDT_3m',
 'USTUSDT_4h',
 'USTUSDT_5m',
 'USTUSDT_6h',
 'USTUSDT_8h',
 'VETUSDT_12h',
 'VETUSDT_15m',
 'VETUSDT_1d',
 'VETUSDT_1h',
 'VETUSDT_1m',
 'VETUSDT_1w',
 'VETUSDT_2h',
 'VETUSDT_30m',
 'VETUSDT_3d',
 'VETUSDT_3m',
 'VETUSDT_4h',
 'VETUSDT_5m',
 'VETUSDT_6h',
 'VETUSDT_8h',
 'WAVESUSDT_12h',
 'WAVESUSDT_15m',
 'WAVESUSDT_1d',
 'WAVESUSDT_1h',
 'WAVESUSDT_1m',
 'WAVESUSDT_1w',
 'WAVESUSDT_2h',
 'WAVESUSDT_30m',
 'WAVESUSDT_3d',
 'WAVESUSDT_3m',
 'WAVESUSDT_4h',
 'WAVESUSDT_5m',
 'WAVESUSDT_6h',
 'WAVESUSDT_8h',
 'XMRUSDT_12h',
 'XMRUSDT_15m',
 'XMRUSDT_1d',
 'XMRUSDT_1h',
 'XMRUSDT_1m',
 'XMRUSDT_1w',
 'XMRUSDT_2h',
 'XMRUSDT_30m',
 'XMRUSDT_3d',
 'XMRUSDT_3m',
 'XMRUSDT_4h',
 'XMRUSDT_5m',
 'XMRUSDT_6h',
 'XMRUSDT_8h',
 'XRPUSDT_12h',
 'XRPUSDT_15m',
 'XRPUSDT_1d',
 'XRPUSDT_1h',
 'XRPUSDT_1m',
 'XRPUSDT_1w',
 'XRPUSDT_2h',
 'XRPUSDT_30m',
 'XRPUSDT_3d',
 'XRPUSDT_3m',
 'XRPUSDT_4h',
 'XRPUSDT_5m',
 'XRPUSDT_6h',
 'XRPUSDT_8h',
 'ZILUSDT_12h',
 'ZILUSDT_15m',
 'ZILUSDT_1d',
 'ZILUSDT_1h',
 'ZILUSDT_1m',
 'ZILUSDT_1w',
 'ZILUSDT_2h',
 'ZILUSDT_30m',
 'ZILUSDT_3d',
 'ZILUSDT_3m',
 'ZILUSDT_4h',
 'ZILUSDT_5m',
 'ZILUSDT_6h',
 'ZILUSDT_8h')